version: '3.8'

services:
  db:
    build:
      context: ./Backend
      dockerfile: database/Dockerfile
    container_name: petsitters_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_HOST_PORT}:5432"
    volumes:
      - ./Backend/database/backup.sql:/docker-entrypoint-initdb.d/backup.sql

  api:
    build:
      context: ./Backend
      dockerfile: app/Dockerfile
    container_name: petsitters_api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DB_HOST_PORT=${DB_HOST_PORT}
      - API_HOST_PORT=${API_HOST_PORT}
      - DEBUG=${DEBUG}
      - POSTGRES_DEBUG=${POSTGRES_DEBUG}
    ports:
      - "${API_HOST_PORT}:8000"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: petsitter_frontend
    ports:
      - '80:80'
    depends_on:
      - api
